-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cpu_option
(
    cpu_option_id uuid NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    cores integer,
    threads integer,
    base_clock numeric(4, 2),
    turbo_clock numeric(4, 2),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT cpu_option_pkey PRIMARY KEY (cpu_option_id)
);

CREATE TABLE IF NOT EXISTS public.employee
(
    employee_id uuid NOT NULL,
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    alias character varying(25) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default",
    last_name character varying(100) COLLATE pg_catalog."default",
    role character varying(100) COLLATE pg_catalog."default",
    department character varying(100) COLLATE pg_catalog."default",
    location character varying(100) COLLATE pg_catalog."default",
    level character varying(50) COLLATE pg_catalog."default",
    start_date date,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT employee_pkey PRIMARY KEY (employee_id)
);

CREATE TABLE IF NOT EXISTS public.ram_option
(
    ram_option_id uuid NOT NULL,
    size_gb integer,
    type character varying(20) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ram_option_pkey PRIMARY KEY (ram_option_id)
);

CREATE TABLE IF NOT EXISTS public.storage_option
(
    storage_option_id uuid NOT NULL,
    name character varying(100) COLLATE pg_catalog."default",
    capacity_gb integer,
    type character varying(20) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT storage_option_pkey PRIMARY KEY (storage_option_id)
);

CREATE TABLE IF NOT EXISTS public.device
(
    device_id uuid,
    employee_id uuid,
    catalog_id uuid[],
    asset_tag character varying(25)[],
    procurement_date timestamp with time zone[],
    storage_option_id uuid,
    ram_option_id uuid,
    cpu_option_id uuid,
    created_at time without time zone,
    PRIMARY KEY (device_id),
    UNIQUE (ram_option_id),
    UNIQUE (cpu_option_id),
    UNIQUE (storage_option_id),
    UNIQUE (catalog_id)
);

CREATE TABLE IF NOT EXISTS public.catalog
(
    catalog_id uuid,
    sku character varying(30)[],
    laptop_name character varying(30)[],
    vendor character varying(30)[],
    category character varying(20)[],
    base_price numeric(8, 2)[],
    is_available bit,
    PRIMARY KEY (catalog_id)
);

ALTER TABLE IF EXISTS public.employee
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.device (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.device
    ADD FOREIGN KEY (ram_option_id)
    REFERENCES public.ram_option (ram_option_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.device
    ADD FOREIGN KEY (cpu_option_id)
    REFERENCES public.cpu_option (cpu_option_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.device
    ADD FOREIGN KEY (storage_option_id)
    REFERENCES public.storage_option (storage_option_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.device
    ADD FOREIGN KEY (catalog_id)
    REFERENCES public.catalog (catalog_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;