-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.device
(
    device_id uuid NOT NULL,
    employee_id uuid,
    catalog_id uuid,
    asset_tag character varying(25)[] COLLATE pg_catalog."default",
    procurement_date timestamp with time zone[],
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT device_pkey PRIMARY KEY (device_id)
);

CREATE TABLE IF NOT EXISTS public.employee
(
    employee_id uuid NOT NULL,
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    alias character varying(25) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default",
    last_name character varying(100) COLLATE pg_catalog."default",
    role character varying(100) COLLATE pg_catalog."default",
    department character varying(100) COLLATE pg_catalog."default",
    location character varying(100) COLLATE pg_catalog."default",
    level character varying(50) COLLATE pg_catalog."default",
    start_date date,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT employee_pkey PRIMARY KEY (employee_id)
);

CREATE TABLE IF NOT EXISTS public.catalog
(
    catalog_id uuid NOT NULL,
    sku character varying(30) COLLATE pg_catalog."default" NOT NULL,
    model_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    vendor character varying(50) COLLATE pg_catalog."default",
    category character varying(30) COLLATE pg_catalog."default",
    cpu character varying(100) COLLATE pg_catalog."default",
    ram character varying(20) COLLATE pg_catalog."default",
    storage character varying(20) COLLATE pg_catalog."default",
    display_size character varying(20) COLLATE pg_catalog."default",
    display_resolution character varying(30) COLLATE pg_catalog."default",
    gpu character varying(100) COLLATE pg_catalog."default",
    base_price numeric(8, 2),
    warranty_months integer,
    is_active boolean DEFAULT true,
    metadata jsonb DEFAULT '{}'::jsonb,
    tags text[] COLLATE pg_catalog."default",
    recommended_for_roles text[] COLLATE pg_catalog."default",
    rating_score numeric(4, 2),
    is_recommended boolean DEFAULT false,
    last_reviewed_at timestamp with time zone,
    embedding vector(1536),
    embedding_model character varying(100) COLLATE pg_catalog."default",
    last_embedded_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT catalog_pkey PRIMARY KEY (catalog_id),
    CONSTRAINT catalog_sku_key UNIQUE (sku)
);

ALTER TABLE IF EXISTS public.device
    ADD CONSTRAINT fk_device_employee FOREIGN KEY (employee_id)
    REFERENCES public.employee (employee_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.device
    ADD FOREIGN KEY (catalog_id)
    REFERENCES public.catalog (catalog_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;